### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by SoneeJohn** [chuckhoupt/jekyll-apple-help#1]
When I do, "Add product MyAppHelp.help to app target (via File Inspector)"

I get a build failed but, now error message appears. Please help.
![screen shot 2015-05-04 at 3 10 09 pm](https://cloud.githubusercontent.com/assets/4827301/7460289/d6d3b1d8-f26f-11e4-9448-7f7095bba493.png)

**Comment by chuckhoupt** [comment]
It looks like you have the Target Membership reversed. MyAppHelp should be a member of MyApp.

You'll want to select MyAppHelp.help in Products on the left, then check MyApp in the Target Membership on the right. Here's a screenshot:

![screen shot 2015-05-04 at 6 28 57 pm](https://cloud.githubusercontent.com/assets/1627217/7463900/a0261fa6-f28b-11e4-9f59-cd9c55933b1e.png)

**Comment by SoneeJohn** [comment]
Can you expand the MyAppHelp folder or send me a copy of that test app?

**Comment by SoneeJohn** [comment]
Okay here are some screenshots of my set up and the problems. I'm having.

![screen shot 2015-05-04 at 6 50 11 pm](https://cloud.githubusercontent.com/assets/4827301/7464183/a5f85eb4-f28e-11e4-9573-d7b907914a1f.png)
![screen shot 2015-05-04 at 6 50 35 pm](https://cloud.githubusercontent.com/assets/4827301/7464182/a5f468ea-f28e-11e4-962f-485a6bb496b6.png)

**Comment by SoneeJohn** [comment]
Here is my test repo:
https://github.com/SoneeJohn/MyApp

Something is wrong with my config.

**Comment by chuckhoupt** [comment]
I added the finished MyApp Example project to the repo for comparison. I'll examine your version..

**Comment by SoneeJohn** [comment]
It turns out that I forgot to install Jekyll. I am very sorry for wasting your time, by the way, thanks for this awesome repo :)

**Comment by chuckhoupt** [comment]
No problem. It is very useful to hear where the doc is unclear. You're one of the first to try out JAH, so I appreciate you being a tenacious trailblazer.

I learned that I should have made the finished MyApp project available from the start and I'll definitely add some screenshots and maybe vids of the setup process.
