### ISSUE TITLE
Internationalization and shell script error (exit code 2)

### ISSUE THREAD

**Issue by yellow8** [chuckhoupt/jekyll-apple-help#15]
Hello,

I've recently internationalized my app.
However, I do not exactly know how to proceed for the help book.
I created a fr.lproj folder next to the default _English.lproj, but then I get the following error:

![script_error](https://user-images.githubusercontent.com/11391557/27473259-c7eef2c6-57fe-11e7-9b4c-9c233961722b.png)

Here are my Xcode internationalization settings:

![xcode_int_settings](https://user-images.githubusercontent.com/11391557/27473282-e097d112-57fe-11e7-935e-3eba512d2733.png)

Any idea what's happening here?

Thanks !

**Comment by chuckhoupt** [comment]
@yellow8 The language lproj folders need to have a name starting with an underscore ("_"). Also Jekyll-Apple-Help expects the names "English/French/German/etc" (that can be changed in config.yml). So try naming the folder "_French.lproj".

**Comment by yellow8** [comment]
Thanks ! that was it 👍
