### ISSUE TITLE
OS X 10.11 El Capitan Compatibility

### ISSUE THREAD

**Issue by SoneeJohn** [chuckhoupt/jekyll-apple-help#6]
The project relies on running this command:
`/usr/bin/make -C "$(dirname "$PRODUCT_SETTINGS_PATH")"`
This works fine for users who are compiling the project on systems lower than OS X 10.11. However, on OS X 10.11 due to the new 'rootless' feature this will not work. From an [article](http://www.macworld.com/article/2948140/os-x/private-i-el-capitans-system-integrity-protection-will-shift-utilities-functions.html) on Macworld, "The specifics of System Integrity Protection are that no user, application, or process will be able to write files or modify files in the root System folder or the /bin, /sbin, and /usr directories, which are hidden by default in OS X’s Finder. The /usr/local folder remains accessible, however; it’s a long-running convention in Unix and variants as a place to stash material and software that individual users rely on."

I tried disabling System Integrity Protection via the recovery partition but, that does not help. Therefore, I suggest having the command run from a different directory?

**Comment by iosdev-republicofapps** [comment]
But this doesn't write to or modify files in /usr/bin does it?  It just runs make from there ...

**Comment by SoneeJohn** [comment]
This is running Xcode 7 on OS X 10.11 El Capitan, I used the Sample App Included in the project and it failed.
![screen shot 2015-09-23 at 7 18 35 pm](https://cloud.githubusercontent.com/assets/4827301/10061565/f98ace0a-6227-11e5-99a0-c5ad1ec2d277.png)

**Comment by iosdev-republicofapps** [comment]
Try gem install jekyll.

**Comment by chuckhoupt** [comment]
Sorry for the delay. I check on El Capitan. After installing Xcode and Jekyll (`sudo gem install jekyll`), the sample app built correctly.

To make the requirements clearer, I've added a check to the makefile which will give a more readable error when Jekyll isn't installed: 8a7c85aa2c4a696a05484a87102045cabf28ceba

**Comment by SoneeJohn** [comment]
Thanks, after reinstalling the gem it worked. I'm very sorry for all the trouble I may have caused :)
